name: ayeayecaptain_mobile
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  redux_logging: ^0.5.1
  flutter_secure_storage: ^9.2.4
  dio_smart_retry: ^7.0.1
  markdown_editable_textinput: ^2.2.0
  flutter_markdown: ^0.7.6+1
  image_picker: ^1.1.2
  file_picker: ^8.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  
  uses-material-design: true