name: ayeayecaptain_mobile
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  json_annotation: ^4.8.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  get_it: ^7.6.4
  equatable: ^2.0.3
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  redux_logging: ^0.5.0
  flutter_secure_storage: ^9.0.0
  dio_smart_retry: ^6.0.0
  markdown_editable_textinput: ^2.2.0
  flutter_markdown: ^0.6.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  
  uses-material-design: true